package com.my.pojo;

import java.util.Date;

public class TAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String busable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String detailDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_ADMIN.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.GUID
     *
     * @return the value of T_ADMIN.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.GUID
     *
     * @param guid the value for T_ADMIN.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.LOGIN_NAME
     *
     * @return the value of T_ADMIN.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.LOGIN_NAME
     *
     * @param loginName the value for T_ADMIN.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.LOGIN_PWD
     *
     * @return the value of T_ADMIN.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.LOGIN_PWD
     *
     * @param loginPwd the value for T_ADMIN.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.NAME
     *
     * @return the value of T_ADMIN.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.NAME
     *
     * @param name the value for T_ADMIN.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.BUSABLE
     *
     * @return the value of T_ADMIN.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBusable() {
        return busable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.BUSABLE
     *
     * @param busable the value for T_ADMIN.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBusable(String busable) {
        this.busable = busable == null ? null : busable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.DETAIL_DES
     *
     * @return the value of T_ADMIN.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDetailDes() {
        return detailDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.DETAIL_DES
     *
     * @param detailDes the value for T_ADMIN.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDetailDes(String detailDes) {
        this.detailDes = detailDes == null ? null : detailDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_ADMIN.CREATE_TIME
     *
     * @return the value of T_ADMIN.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_ADMIN.CREATE_TIME
     *
     * @param createTime the value for T_ADMIN.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}