package com.my.pojo;

import java.util.Date;

public class TCacheHistoryPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CACHE_HISTORY_PHOTO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CACHE_HISTORY_PHOTO.HISTORY_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String historyGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_CACHE_HISTORY_PHOTO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CACHE_HISTORY_PHOTO.GUID
     *
     * @return the value of T_CACHE_HISTORY_PHOTO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CACHE_HISTORY_PHOTO.GUID
     *
     * @param guid the value for T_CACHE_HISTORY_PHOTO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CACHE_HISTORY_PHOTO.HISTORY_GUID
     *
     * @return the value of T_CACHE_HISTORY_PHOTO.HISTORY_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getHistoryGuid() {
        return historyGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CACHE_HISTORY_PHOTO.HISTORY_GUID
     *
     * @param historyGuid the value for T_CACHE_HISTORY_PHOTO.HISTORY_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setHistoryGuid(String historyGuid) {
        this.historyGuid = historyGuid == null ? null : historyGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_CACHE_HISTORY_PHOTO.CREATE_TIME
     *
     * @return the value of T_CACHE_HISTORY_PHOTO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_CACHE_HISTORY_PHOTO.CREATE_TIME
     *
     * @param createTime the value for T_CACHE_HISTORY_PHOTO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}