package com.my.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TCompare {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String userGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.CERTID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String certid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.SEX
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.BIRTHDAY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.FORK
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String fork;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.ADDRESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.ISSUE_AUTHORITY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String issueAuthority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.VALID_PRIOD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String validPriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.RETURN_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.RETURN_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String returnInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.CODE1
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String code1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.SIMILARITY1
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal similarity1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.CODE2
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String code2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.SIMILARITY2
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal similarity2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.CODE3
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String code3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.SIMILARITY3
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal similarity3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.SOURCE_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.SOURCE_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String sourceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.IP
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal holdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.GUID
     *
     * @return the value of T_COMPARE.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.GUID
     *
     * @param guid the value for T_COMPARE.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.USER_GUID
     *
     * @return the value of T_COMPARE.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getUserGuid() {
        return userGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.USER_GUID
     *
     * @param userGuid the value for T_COMPARE.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUserGuid(String userGuid) {
        this.userGuid = userGuid == null ? null : userGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.NAME
     *
     * @return the value of T_COMPARE.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.NAME
     *
     * @param name the value for T_COMPARE.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.CERTID
     *
     * @return the value of T_COMPARE.CERTID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCertid() {
        return certid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.CERTID
     *
     * @param certid the value for T_COMPARE.CERTID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCertid(String certid) {
        this.certid = certid == null ? null : certid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.SEX
     *
     * @return the value of T_COMPARE.SEX
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.SEX
     *
     * @param sex the value for T_COMPARE.SEX
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.BIRTHDAY
     *
     * @return the value of T_COMPARE.BIRTHDAY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.BIRTHDAY
     *
     * @param birthday the value for T_COMPARE.BIRTHDAY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.FORK
     *
     * @return the value of T_COMPARE.FORK
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getFork() {
        return fork;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.FORK
     *
     * @param fork the value for T_COMPARE.FORK
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setFork(String fork) {
        this.fork = fork == null ? null : fork.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.ADDRESS
     *
     * @return the value of T_COMPARE.ADDRESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.ADDRESS
     *
     * @param address the value for T_COMPARE.ADDRESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.ISSUE_AUTHORITY
     *
     * @return the value of T_COMPARE.ISSUE_AUTHORITY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIssueAuthority() {
        return issueAuthority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.ISSUE_AUTHORITY
     *
     * @param issueAuthority the value for T_COMPARE.ISSUE_AUTHORITY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIssueAuthority(String issueAuthority) {
        this.issueAuthority = issueAuthority == null ? null : issueAuthority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.VALID_PRIOD
     *
     * @return the value of T_COMPARE.VALID_PRIOD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getValidPriod() {
        return validPriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.VALID_PRIOD
     *
     * @param validPriod the value for T_COMPARE.VALID_PRIOD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setValidPriod(String validPriod) {
        this.validPriod = validPriod == null ? null : validPriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.RETURN_CODE
     *
     * @return the value of T_COMPARE.RETURN_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.RETURN_CODE
     *
     * @param returnCode the value for T_COMPARE.RETURN_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.RETURN_INFO
     *
     * @return the value of T_COMPARE.RETURN_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getReturnInfo() {
        return returnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.RETURN_INFO
     *
     * @param returnInfo the value for T_COMPARE.RETURN_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setReturnInfo(String returnInfo) {
        this.returnInfo = returnInfo == null ? null : returnInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.CODE1
     *
     * @return the value of T_COMPARE.CODE1
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCode1() {
        return code1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.CODE1
     *
     * @param code1 the value for T_COMPARE.CODE1
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCode1(String code1) {
        this.code1 = code1 == null ? null : code1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.SIMILARITY1
     *
     * @return the value of T_COMPARE.SIMILARITY1
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getSimilarity1() {
        return similarity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.SIMILARITY1
     *
     * @param similarity1 the value for T_COMPARE.SIMILARITY1
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSimilarity1(BigDecimal similarity1) {
        this.similarity1 = similarity1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.CODE2
     *
     * @return the value of T_COMPARE.CODE2
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCode2() {
        return code2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.CODE2
     *
     * @param code2 the value for T_COMPARE.CODE2
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCode2(String code2) {
        this.code2 = code2 == null ? null : code2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.SIMILARITY2
     *
     * @return the value of T_COMPARE.SIMILARITY2
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getSimilarity2() {
        return similarity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.SIMILARITY2
     *
     * @param similarity2 the value for T_COMPARE.SIMILARITY2
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSimilarity2(BigDecimal similarity2) {
        this.similarity2 = similarity2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.CODE3
     *
     * @return the value of T_COMPARE.CODE3
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCode3() {
        return code3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.CODE3
     *
     * @param code3 the value for T_COMPARE.CODE3
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCode3(String code3) {
        this.code3 = code3 == null ? null : code3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.SIMILARITY3
     *
     * @return the value of T_COMPARE.SIMILARITY3
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getSimilarity3() {
        return similarity3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.SIMILARITY3
     *
     * @param similarity3 the value for T_COMPARE.SIMILARITY3
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSimilarity3(BigDecimal similarity3) {
        this.similarity3 = similarity3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.SOURCE_CODE
     *
     * @return the value of T_COMPARE.SOURCE_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.SOURCE_CODE
     *
     * @param sourceCode the value for T_COMPARE.SOURCE_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.SOURCE_INFO
     *
     * @return the value of T_COMPARE.SOURCE_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSourceInfo() {
        return sourceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.SOURCE_INFO
     *
     * @param sourceInfo the value for T_COMPARE.SOURCE_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSourceInfo(String sourceInfo) {
        this.sourceInfo = sourceInfo == null ? null : sourceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.IP
     *
     * @return the value of T_COMPARE.IP
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.IP
     *
     * @param ip the value for T_COMPARE.IP
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.HOLD_TIME
     *
     * @return the value of T_COMPARE.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getHoldTime() {
        return holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.HOLD_TIME
     *
     * @param holdTime the value for T_COMPARE.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setHoldTime(BigDecimal holdTime) {
        this.holdTime = holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE.CREATE_TIME
     *
     * @return the value of T_COMPARE.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE.CREATE_TIME
     *
     * @param createTime the value for T_COMPARE.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}