package com.my.pojo;

import java.util.Date;

public class TCompareSuccessPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS_PHOTO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS_PHOTO.SUCCESS_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String successGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS_PHOTO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS_PHOTO.GUID
     *
     * @return the value of T_COMPARE_SUCCESS_PHOTO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS_PHOTO.GUID
     *
     * @param guid the value for T_COMPARE_SUCCESS_PHOTO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS_PHOTO.SUCCESS_GUID
     *
     * @return the value of T_COMPARE_SUCCESS_PHOTO.SUCCESS_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSuccessGuid() {
        return successGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS_PHOTO.SUCCESS_GUID
     *
     * @param successGuid the value for T_COMPARE_SUCCESS_PHOTO.SUCCESS_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSuccessGuid(String successGuid) {
        this.successGuid = successGuid == null ? null : successGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS_PHOTO.CREATE_TIME
     *
     * @return the value of T_COMPARE_SUCCESS_PHOTO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS_PHOTO.CREATE_TIME
     *
     * @param createTime the value for T_COMPARE_SUCCESS_PHOTO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}