package com.my.pojo;

import java.util.Date;

public class TCompareSuccess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_SUCCESS.ID_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.GUID
     *
     * @return the value of T_COMPARE_SUCCESS.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.GUID
     *
     * @param guid the value for T_COMPARE_SUCCESS.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.MOBILE
     *
     * @return the value of T_COMPARE_SUCCESS.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.MOBILE
     *
     * @param mobile the value for T_COMPARE_SUCCESS.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.BAR_CODE
     *
     * @return the value of T_COMPARE_SUCCESS.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.BAR_CODE
     *
     * @param barCode the value for T_COMPARE_SUCCESS.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.NAME
     *
     * @return the value of T_COMPARE_SUCCESS.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.NAME
     *
     * @param name the value for T_COMPARE_SUCCESS.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.ID_NUMBER
     *
     * @return the value of T_COMPARE_SUCCESS.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.ID_NUMBER
     *
     * @param idNumber the value for T_COMPARE_SUCCESS.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.CREATE_TIME
     *
     * @return the value of T_COMPARE_SUCCESS.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.CREATE_TIME
     *
     * @param createTime the value for T_COMPARE_SUCCESS.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_SUCCESS.ID_TYPE
     *
     * @return the value of T_COMPARE_SUCCESS.ID_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_SUCCESS.ID_TYPE
     *
     * @param idType the value for T_COMPARE_SUCCESS.ID_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }
}