package com.my.pojo;

public class TCompareHistoryWithBLOBs extends TCompareHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.PHOTO_ID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.PHOTO_USER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String photoUser;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.PHOTO_ID
     *
     * @return the value of T_COMPARE_HISTORY.PHOTO_ID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.PHOTO_ID
     *
     * @param photoId the value for T_COMPARE_HISTORY.PHOTO_ID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setPhotoId(String photoId) {
        this.photoId = photoId == null ? null : photoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.PHOTO_USER
     *
     * @return the value of T_COMPARE_HISTORY.PHOTO_USER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getPhotoUser() {
        return photoUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.PHOTO_USER
     *
     * @param photoUser the value for T_COMPARE_HISTORY.PHOTO_USER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setPhotoUser(String photoUser) {
        this.photoUser = photoUser == null ? null : photoUser.trim();
    }
}