package com.my.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TCompareHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.SIMILARITY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal similarity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.SUCCESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.RETURN_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String returnCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal holdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.ID_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.SOURCE_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String sourceCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.SOURCE_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String sourceInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_HISTORY.SOURCE_HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal sourceHoldTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.GUID
     *
     * @return the value of T_COMPARE_HISTORY.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.GUID
     *
     * @param guid the value for T_COMPARE_HISTORY.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.MOBILE
     *
     * @return the value of T_COMPARE_HISTORY.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.MOBILE
     *
     * @param mobile the value for T_COMPARE_HISTORY.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.BAR_CODE
     *
     * @return the value of T_COMPARE_HISTORY.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.BAR_CODE
     *
     * @param barCode the value for T_COMPARE_HISTORY.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.NAME
     *
     * @return the value of T_COMPARE_HISTORY.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.NAME
     *
     * @param name the value for T_COMPARE_HISTORY.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.ID_NUMBER
     *
     * @return the value of T_COMPARE_HISTORY.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.ID_NUMBER
     *
     * @param idNumber the value for T_COMPARE_HISTORY.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.SIMILARITY
     *
     * @return the value of T_COMPARE_HISTORY.SIMILARITY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getSimilarity() {
        return similarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.SIMILARITY
     *
     * @param similarity the value for T_COMPARE_HISTORY.SIMILARITY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSimilarity(BigDecimal similarity) {
        this.similarity = similarity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.SUCCESS
     *
     * @return the value of T_COMPARE_HISTORY.SUCCESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.SUCCESS
     *
     * @param success the value for T_COMPARE_HISTORY.SUCCESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSuccess(String success) {
        this.success = success == null ? null : success.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.RETURN_CODE
     *
     * @return the value of T_COMPARE_HISTORY.RETURN_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.RETURN_CODE
     *
     * @param returnCode the value for T_COMPARE_HISTORY.RETURN_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setReturnCode(String returnCode) {
        this.returnCode = returnCode == null ? null : returnCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.HOLD_TIME
     *
     * @return the value of T_COMPARE_HISTORY.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getHoldTime() {
        return holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.HOLD_TIME
     *
     * @param holdTime the value for T_COMPARE_HISTORY.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setHoldTime(BigDecimal holdTime) {
        this.holdTime = holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.CREATE_TIME
     *
     * @return the value of T_COMPARE_HISTORY.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.CREATE_TIME
     *
     * @param createTime the value for T_COMPARE_HISTORY.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.ID_TYPE
     *
     * @return the value of T_COMPARE_HISTORY.ID_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdType() {
        return idType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.ID_TYPE
     *
     * @param idType the value for T_COMPARE_HISTORY.ID_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdType(String idType) {
        this.idType = idType == null ? null : idType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.SOURCE_CODE
     *
     * @return the value of T_COMPARE_HISTORY.SOURCE_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSourceCode() {
        return sourceCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.SOURCE_CODE
     *
     * @param sourceCode the value for T_COMPARE_HISTORY.SOURCE_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSourceCode(String sourceCode) {
        this.sourceCode = sourceCode == null ? null : sourceCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.SOURCE_INFO
     *
     * @return the value of T_COMPARE_HISTORY.SOURCE_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSourceInfo() {
        return sourceInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.SOURCE_INFO
     *
     * @param sourceInfo the value for T_COMPARE_HISTORY.SOURCE_INFO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSourceInfo(String sourceInfo) {
        this.sourceInfo = sourceInfo == null ? null : sourceInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_HISTORY.SOURCE_HOLD_TIME
     *
     * @return the value of T_COMPARE_HISTORY.SOURCE_HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getSourceHoldTime() {
        return sourceHoldTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_HISTORY.SOURCE_HOLD_TIME
     *
     * @param sourceHoldTime the value for T_COMPARE_HISTORY.SOURCE_HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSourceHoldTime(BigDecimal sourceHoldTime) {
        this.sourceHoldTime = sourceHoldTime;
    }
}