package com.my.pojo;

public class TComparePhotoWithBLOBs extends TComparePhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_PHOTO.PHOTO_ID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private byte[] photoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_PHOTO.PHOTO_USER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private byte[] photoUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_COMPARE_PHOTO.PHOTO_CHIP
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private byte[] photoChip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_PHOTO.PHOTO_ID
     *
     * @return the value of T_COMPARE_PHOTO.PHOTO_ID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public byte[] getPhotoId() {
        return photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_PHOTO.PHOTO_ID
     *
     * @param photoId the value for T_COMPARE_PHOTO.PHOTO_ID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setPhotoId(byte[] photoId) {
        this.photoId = photoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_PHOTO.PHOTO_USER
     *
     * @return the value of T_COMPARE_PHOTO.PHOTO_USER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public byte[] getPhotoUser() {
        return photoUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_PHOTO.PHOTO_USER
     *
     * @param photoUser the value for T_COMPARE_PHOTO.PHOTO_USER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setPhotoUser(byte[] photoUser) {
        this.photoUser = photoUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_COMPARE_PHOTO.PHOTO_CHIP
     *
     * @return the value of T_COMPARE_PHOTO.PHOTO_CHIP
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public byte[] getPhotoChip() {
        return photoChip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_COMPARE_PHOTO.PHOTO_CHIP
     *
     * @param photoChip the value for T_COMPARE_PHOTO.PHOTO_CHIP
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setPhotoChip(byte[] photoChip) {
        this.photoChip = photoChip;
    }
}