package com.my.pojo;

import java.util.Date;

public class TMobileInfoInput {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.SECRET_KEY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String secretKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.GENDER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.DEPARTMENT
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.DUTIES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String duties;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String busable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String detailDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String userGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.BANK_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_MOBILE_INFO_INPUT.SECRET_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String secretType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.GUID
     *
     * @return the value of T_MOBILE_INFO_INPUT.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.GUID
     *
     * @param guid the value for T_MOBILE_INFO_INPUT.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.MOBILE
     *
     * @return the value of T_MOBILE_INFO_INPUT.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.MOBILE
     *
     * @param mobile the value for T_MOBILE_INFO_INPUT.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.SECRET_KEY
     *
     * @return the value of T_MOBILE_INFO_INPUT.SECRET_KEY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSecretKey() {
        return secretKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.SECRET_KEY
     *
     * @param secretKey the value for T_MOBILE_INFO_INPUT.SECRET_KEY
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSecretKey(String secretKey) {
        this.secretKey = secretKey == null ? null : secretKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.NAME
     *
     * @return the value of T_MOBILE_INFO_INPUT.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.NAME
     *
     * @param name the value for T_MOBILE_INFO_INPUT.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.GENDER
     *
     * @return the value of T_MOBILE_INFO_INPUT.GENDER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.GENDER
     *
     * @param gender the value for T_MOBILE_INFO_INPUT.GENDER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.ID_NUMBER
     *
     * @return the value of T_MOBILE_INFO_INPUT.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.ID_NUMBER
     *
     * @param idNumber the value for T_MOBILE_INFO_INPUT.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.DEPARTMENT
     *
     * @return the value of T_MOBILE_INFO_INPUT.DEPARTMENT
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.DEPARTMENT
     *
     * @param department the value for T_MOBILE_INFO_INPUT.DEPARTMENT
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.DUTIES
     *
     * @return the value of T_MOBILE_INFO_INPUT.DUTIES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDuties() {
        return duties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.DUTIES
     *
     * @param duties the value for T_MOBILE_INFO_INPUT.DUTIES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDuties(String duties) {
        this.duties = duties == null ? null : duties.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.BUSABLE
     *
     * @return the value of T_MOBILE_INFO_INPUT.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBusable() {
        return busable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.BUSABLE
     *
     * @param busable the value for T_MOBILE_INFO_INPUT.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBusable(String busable) {
        this.busable = busable == null ? null : busable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.DETAIL_DES
     *
     * @return the value of T_MOBILE_INFO_INPUT.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDetailDes() {
        return detailDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.DETAIL_DES
     *
     * @param detailDes the value for T_MOBILE_INFO_INPUT.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDetailDes(String detailDes) {
        this.detailDes = detailDes == null ? null : detailDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.USER_GUID
     *
     * @return the value of T_MOBILE_INFO_INPUT.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getUserGuid() {
        return userGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.USER_GUID
     *
     * @param userGuid the value for T_MOBILE_INFO_INPUT.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUserGuid(String userGuid) {
        this.userGuid = userGuid == null ? null : userGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.CREATE_TIME
     *
     * @return the value of T_MOBILE_INFO_INPUT.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.CREATE_TIME
     *
     * @param createTime the value for T_MOBILE_INFO_INPUT.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.BANK_NAME
     *
     * @return the value of T_MOBILE_INFO_INPUT.BANK_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.BANK_NAME
     *
     * @param bankName the value for T_MOBILE_INFO_INPUT.BANK_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_MOBILE_INFO_INPUT.SECRET_TYPE
     *
     * @return the value of T_MOBILE_INFO_INPUT.SECRET_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSecretType() {
        return secretType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_MOBILE_INFO_INPUT.SECRET_TYPE
     *
     * @param secretType the value for T_MOBILE_INFO_INPUT.SECRET_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSecretType(String secretType) {
        this.secretType = secretType == null ? null : secretType.trim();
    }
}