package com.my.pojo;

import java.math.BigDecimal;
import java.util.Date;

public class TOcrHistory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String barCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.SUCCESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String success;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private BigDecimal holdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_OCR_HISTORY.ID_PHOTO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.GUID
     *
     * @return the value of T_OCR_HISTORY.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.GUID
     *
     * @param guid the value for T_OCR_HISTORY.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.MOBILE
     *
     * @return the value of T_OCR_HISTORY.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.MOBILE
     *
     * @param mobile the value for T_OCR_HISTORY.MOBILE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.BAR_CODE
     *
     * @return the value of T_OCR_HISTORY.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBarCode() {
        return barCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.BAR_CODE
     *
     * @param barCode the value for T_OCR_HISTORY.BAR_CODE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBarCode(String barCode) {
        this.barCode = barCode == null ? null : barCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.NAME
     *
     * @return the value of T_OCR_HISTORY.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.NAME
     *
     * @param name the value for T_OCR_HISTORY.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.ID_NUMBER
     *
     * @return the value of T_OCR_HISTORY.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.ID_NUMBER
     *
     * @param idNumber the value for T_OCR_HISTORY.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.SUCCESS
     *
     * @return the value of T_OCR_HISTORY.SUCCESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSuccess() {
        return success;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.SUCCESS
     *
     * @param success the value for T_OCR_HISTORY.SUCCESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSuccess(String success) {
        this.success = success == null ? null : success.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.HOLD_TIME
     *
     * @return the value of T_OCR_HISTORY.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public BigDecimal getHoldTime() {
        return holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.HOLD_TIME
     *
     * @param holdTime the value for T_OCR_HISTORY.HOLD_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setHoldTime(BigDecimal holdTime) {
        this.holdTime = holdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.CREATE_TIME
     *
     * @return the value of T_OCR_HISTORY.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.CREATE_TIME
     *
     * @param createTime the value for T_OCR_HISTORY.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_OCR_HISTORY.ID_PHOTO
     *
     * @return the value of T_OCR_HISTORY.ID_PHOTO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdPhoto() {
        return idPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_OCR_HISTORY.ID_PHOTO
     *
     * @param idPhoto the value for T_OCR_HISTORY.ID_PHOTO
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdPhoto(String idPhoto) {
        this.idPhoto = idPhoto == null ? null : idPhoto.trim();
    }
}