package com.my.pojo;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.PASSWORD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.GENDER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.DEPARTMENT
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String department;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String busable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String detailDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String userGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.SECRET_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String secretType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.GUID
     *
     * @return the value of T_USER.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.GUID
     *
     * @param guid the value for T_USER.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.LOGIN_NAME
     *
     * @return the value of T_USER.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.LOGIN_NAME
     *
     * @param loginName the value for T_USER.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.PASSWORD
     *
     * @return the value of T_USER.PASSWORD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.PASSWORD
     *
     * @param password the value for T_USER.PASSWORD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.NAME
     *
     * @return the value of T_USER.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.NAME
     *
     * @param name the value for T_USER.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.GENDER
     *
     * @return the value of T_USER.GENDER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.GENDER
     *
     * @param gender the value for T_USER.GENDER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.ID_NUMBER
     *
     * @return the value of T_USER.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getIdNumber() {
        return idNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.ID_NUMBER
     *
     * @param idNumber the value for T_USER.ID_NUMBER
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber == null ? null : idNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.DEPARTMENT
     *
     * @return the value of T_USER.DEPARTMENT
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.DEPARTMENT
     *
     * @param department the value for T_USER.DEPARTMENT
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDepartment(String department) {
        this.department = department == null ? null : department.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.BUSABLE
     *
     * @return the value of T_USER.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBusable() {
        return busable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.BUSABLE
     *
     * @param busable the value for T_USER.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBusable(String busable) {
        this.busable = busable == null ? null : busable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.DETAIL_DES
     *
     * @return the value of T_USER.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDetailDes() {
        return detailDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.DETAIL_DES
     *
     * @param detailDes the value for T_USER.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDetailDes(String detailDes) {
        this.detailDes = detailDes == null ? null : detailDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.USER_GUID
     *
     * @return the value of T_USER.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getUserGuid() {
        return userGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.USER_GUID
     *
     * @param userGuid the value for T_USER.USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUserGuid(String userGuid) {
        this.userGuid = userGuid == null ? null : userGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.CREATE_TIME
     *
     * @return the value of T_USER.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.CREATE_TIME
     *
     * @param createTime the value for T_USER.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.SECRET_TYPE
     *
     * @return the value of T_USER.SECRET_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getSecretType() {
        return secretType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.SECRET_TYPE
     *
     * @param secretType the value for T_USER.SECRET_TYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setSecretType(String secretType) {
        this.secretType = secretType == null ? null : secretType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER.UPDATE_TIME
     *
     * @return the value of T_USER.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER.UPDATE_TIME
     *
     * @param updateTime the value for T_USER.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}