package com.my.pojo;

public class TUserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.ETYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String etype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.EROLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String erole;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String busable;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String detailDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.CREATE_USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String createUserGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.CREATE_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String createName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.UPDATE_USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String updateUserGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.UPDATE_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String updateName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_INFO.PROJECT_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String projectGuid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.GUID
     *
     * @return the value of T_USER_INFO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.GUID
     *
     * @param guid the value for T_USER_INFO.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.LOGIN_NAME
     *
     * @return the value of T_USER_INFO.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.LOGIN_NAME
     *
     * @param loginName the value for T_USER_INFO.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.LOGIN_PWD
     *
     * @return the value of T_USER_INFO.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.LOGIN_PWD
     *
     * @param loginPwd the value for T_USER_INFO.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.NAME
     *
     * @return the value of T_USER_INFO.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.NAME
     *
     * @param name the value for T_USER_INFO.NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.ETYPE
     *
     * @return the value of T_USER_INFO.ETYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getEtype() {
        return etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.ETYPE
     *
     * @param etype the value for T_USER_INFO.ETYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setEtype(String etype) {
        this.etype = etype == null ? null : etype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.EROLE
     *
     * @return the value of T_USER_INFO.EROLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getErole() {
        return erole;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.EROLE
     *
     * @param erole the value for T_USER_INFO.EROLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setErole(String erole) {
        this.erole = erole == null ? null : erole.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.BUSABLE
     *
     * @return the value of T_USER_INFO.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getBusable() {
        return busable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.BUSABLE
     *
     * @param busable the value for T_USER_INFO.BUSABLE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setBusable(String busable) {
        this.busable = busable == null ? null : busable.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.DETAIL_DES
     *
     * @return the value of T_USER_INFO.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDetailDes() {
        return detailDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.DETAIL_DES
     *
     * @param detailDes the value for T_USER_INFO.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDetailDes(String detailDes) {
        this.detailDes = detailDes == null ? null : detailDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.CREATE_TIME
     *
     * @return the value of T_USER_INFO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.CREATE_TIME
     *
     * @param createTime the value for T_USER_INFO.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.CREATE_USER_GUID
     *
     * @return the value of T_USER_INFO.CREATE_USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCreateUserGuid() {
        return createUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.CREATE_USER_GUID
     *
     * @param createUserGuid the value for T_USER_INFO.CREATE_USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateUserGuid(String createUserGuid) {
        this.createUserGuid = createUserGuid == null ? null : createUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.CREATE_NAME
     *
     * @return the value of T_USER_INFO.CREATE_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCreateName() {
        return createName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.CREATE_NAME
     *
     * @param createName the value for T_USER_INFO.CREATE_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateName(String createName) {
        this.createName = createName == null ? null : createName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.UPDATE_TIME
     *
     * @return the value of T_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.UPDATE_TIME
     *
     * @param updateTime the value for T_USER_INFO.UPDATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime == null ? null : updateTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.UPDATE_USER_GUID
     *
     * @return the value of T_USER_INFO.UPDATE_USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getUpdateUserGuid() {
        return updateUserGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.UPDATE_USER_GUID
     *
     * @param updateUserGuid the value for T_USER_INFO.UPDATE_USER_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUpdateUserGuid(String updateUserGuid) {
        this.updateUserGuid = updateUserGuid == null ? null : updateUserGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.UPDATE_NAME
     *
     * @return the value of T_USER_INFO.UPDATE_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getUpdateName() {
        return updateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.UPDATE_NAME
     *
     * @param updateName the value for T_USER_INFO.UPDATE_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setUpdateName(String updateName) {
        this.updateName = updateName == null ? null : updateName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_INFO.PROJECT_GUID
     *
     * @return the value of T_USER_INFO.PROJECT_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getProjectGuid() {
        return projectGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_INFO.PROJECT_GUID
     *
     * @param projectGuid the value for T_USER_INFO.PROJECT_GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setProjectGuid(String projectGuid) {
        this.projectGuid = projectGuid == null ? null : projectGuid.trim();
    }
}