package com.my.pojo;

public class TUserLoginLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.ADDRESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.ETYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String etype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.LOGIN_OUT_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String loginOutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_USER_LOGIN_LOG.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    private String detailDes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.GUID
     *
     * @return the value of T_USER_LOGIN_LOG.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.GUID
     *
     * @param guid the value for T_USER_LOGIN_LOG.GUID
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.LOGIN_NAME
     *
     * @return the value of T_USER_LOGIN_LOG.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.LOGIN_NAME
     *
     * @param loginName the value for T_USER_LOGIN_LOG.LOGIN_NAME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.LOGIN_PWD
     *
     * @return the value of T_USER_LOGIN_LOG.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.LOGIN_PWD
     *
     * @param loginPwd the value for T_USER_LOGIN_LOG.LOGIN_PWD
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd == null ? null : loginPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.ADDRESS
     *
     * @return the value of T_USER_LOGIN_LOG.ADDRESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.ADDRESS
     *
     * @param address the value for T_USER_LOGIN_LOG.ADDRESS
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.ETYPE
     *
     * @return the value of T_USER_LOGIN_LOG.ETYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getEtype() {
        return etype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.ETYPE
     *
     * @param etype the value for T_USER_LOGIN_LOG.ETYPE
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setEtype(String etype) {
        this.etype = etype == null ? null : etype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.CREATE_TIME
     *
     * @return the value of T_USER_LOGIN_LOG.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.CREATE_TIME
     *
     * @param createTime the value for T_USER_LOGIN_LOG.CREATE_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime == null ? null : createTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.LOGIN_OUT_TIME
     *
     * @return the value of T_USER_LOGIN_LOG.LOGIN_OUT_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getLoginOutTime() {
        return loginOutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.LOGIN_OUT_TIME
     *
     * @param loginOutTime the value for T_USER_LOGIN_LOG.LOGIN_OUT_TIME
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setLoginOutTime(String loginOutTime) {
        this.loginOutTime = loginOutTime == null ? null : loginOutTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_USER_LOGIN_LOG.DETAIL_DES
     *
     * @return the value of T_USER_LOGIN_LOG.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public String getDetailDes() {
        return detailDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_USER_LOGIN_LOG.DETAIL_DES
     *
     * @param detailDes the value for T_USER_LOGIN_LOG.DETAIL_DES
     *
     * @mbggenerated Tue Jun 19 16:57:40 CST 2018
     */
    public void setDetailDes(String detailDes) {
        this.detailDes = detailDes == null ? null : detailDes.trim();
    }
}